version: "3.6"
services:
  Syncthing:
    container_name: "Syncthing"
    entrypoint:
      - "/init"
    environment:
      - "TZ=Europe/Rome"
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/config"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
    hostname: "Syncthing"
    image: "linuxserver/syncthing:latest"
    ipc: "private"
    labels:
      build_version: "Linuxserver.io version:- v1.23.1-ls92 Build-date:- 2023-02-15T01:42:08-06:00"
      casaos: "casaos"
      custom_id: "acb25eec-eeec-4fe9-bb2d-d5677901795d"
      desc: "Syncthing is a continuous file synchronization program. It synchronizes\
        \ files between two or more computers in real time, safely protected from\
        \ prying eyes. Your data is your data alone and you deserve to choose where\
        \ it is stored, whether it is shared with some third party, and how it's transmitted\
        \ over the internet."
      host: ""
      icon: "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Syncthing/icon.png"
      index: "/"
      io.casaos.v1.app.store.id: "74"
      maintainer: "thelamer"
      name: "Syncthing"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-02-15T01:42:08-06:00"
      org.opencontainers.image.description: "[Syncthing](https://syncthing.net) replaces\
        \ proprietary sync and cloud services with something open, trustworthy and\
        \ decentralized. Your data is your data alone and you deserve to choose where\
        \ it is stored, if it is shared with some third party and how it's transmitted\
        \ over the Internet."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-syncthing"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "dfac742c64a3503637ebae8b9d667c3d21d391c1"
      org.opencontainers.image.revision: "dfac742c64a3503637ebae8b9d667c3d21d391c1"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-syncthing"
      org.opencontainers.image.title: "Syncthing"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-syncthing/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v1.23.1-ls92"
      origin: "official"
      protocol: "http"
      show_env: "casaos,TZ,PUID,PGID"
      web: "8384"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:03"
    network_mode: "bridge"
    ports:
      - "21027:21027/udp"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "8384:8384/tcp"
    restart: "always"
    volumes:
      - "/DATA:/DATA"
      - "/DATA/AppData/Syncthing/config:/config"
    working_dir: "/"
  homeassistant:
    container_name: "homeassistant"
    entrypoint:
      - "/init"
    environment:
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_CMD_WAIT_FOR_SERVICES=1"
      - "S6_SERVICES_READYTIME=50"
      - "WHEELS_LINKS=https://wheels.home-assistant.io/musllinux/"
      - "S6_SERVICES_GRACETIME=220000"
    hostname: "raspberrypi4"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ipc: "private"
    labels:
      casaos: "casaos"
      com.docker.compose.config-hash: "2ad4214b9260f1992097467c4bd10475f2b667ce69627cc46dd429429f3c0064"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:481c1299b64a85f29fa0e9e6daebeeb55a11fcdf5680dd7b54d8181972d11853"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "homeserver"
      com.docker.compose.project.config_files: "/home/pi/homeserver/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/home/pi/homeserver"
      com.docker.compose.service: "homeassistant"
      com.docker.compose.version: "2.14.1"
      custom_id: "bfc85c8e-d522-460c-8bd0-217c2b558b9e"
      desc: ""
      host: "192.168.1.10"
      icon: "https://icon.casaos.io/main/all/home-assistant.png"
      index: ""
      io.casaos.v1.app.store.id: "0"
      io.hass.arch: "aarch64"
      io.hass.base.arch: "aarch64"
      io.hass.base.image: "homeassistant/aarch64-base:3.16"
      io.hass.base.name: "python"
      io.hass.base.version: "2022.11.0"
      io.hass.type: "core"
      io.hass.version: "2023.1.4"
      name: "homeassistant"
      org.opencontainers.image.authors: "The Home Assistant Authors"
      org.opencontainers.image.created: "2023-01-12 20:03:08+00:00"
      org.opencontainers.image.description: "Open-source home automation platform\
        \ running on Python 3"
      org.opencontainers.image.documentation: "https://www.home-assistant.io/docs/"
      org.opencontainers.image.licenses: "Apache License 2.0"
      org.opencontainers.image.source: "https://github.com/home-assistant/core"
      org.opencontainers.image.title: "Home Assistant"
      org.opencontainers.image.url: "https://www.home-assistant.io/"
      org.opencontainers.image.version: "2023.1.4"
      origin: "local"
      protocol: "http"
      show_env: "casaos,PATH,LANG,S6_BEHAVIOUR_IF_STAGE2_FAILS,S6_CMD_WAIT_FOR_SERVICES_MAXTIME,S6_CMD_WAIT_FOR_SERVICES,S6_SERVICES_READYTIME,WHEELS_LINKS,S6_SERVICES_GRACETIME"
      web: "8123"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "host"
    privileged: true
    restart: "unless-stopped"
    security_opt:
      - "label=disable"
    volumes:
      - "/home/pi/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime"
    working_dir: "/config"
  netdata:
    container_name: "netdata"
    entrypoint:
      - "/usr/sbin/run.sh"
    environment:
      - "NETDATA_CLAIM_URL=https://app.netdata.cloud"
      - "NETDATA_CLAIM_TOKEN=xyNFYzjXx0O2cYJnfShyCaQWR4Zvvn75cSp3MulZbj81dEqmZyQ5ePW_d9qmF_qMtwxao1-fLu1SVpURfGZysd-y5D4TPuHkErU9DIUswUAiYFn__numT9kH4gPwsV9mE7UApi8"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NETDATA_OFFICIAL_IMAGE=true"
      - "DOCKER_GRP=netdata"
      - "DOCKER_USR=netdata"
      - "NETDATA_LISTENER_PORT=19999"
    expose:
      - "19999/tcp"
    hostname: "raspberrypi4.local"
    image: "netdata/netdata"
    ipc: "private"
    labels:
      casaos: "casaos"
      com.docker.compose.config-hash: "6836dd3ac428cb5873f99e77455289abc1180637483d623d25fe1c7bd9724837"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:dba1d6fd8a857f75428a1479663955c00ceab0cd345645d2af45c21620b59707"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "netdata"
      com.docker.compose.project.config_files: "/home/pi/homeserver/netdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/home/pi/homeserver/netdata"
      com.docker.compose.service: "netdata"
      com.docker.compose.version: "2.15.1"
      custom_id: "44ca8c74-5ec7-4de9-a3f1-0acbf64d6998"
      desc: ""
      host: "192.168.1.10"
      icon: "https://icon.casaos.io/main/all/netdata.png"
      index: ""
      io.casaos.v1.app.store.id: "0"
      name: "netdata"
      origin: "local"
      protocol: "http"
      show_env: "casaos,NETDATA_CLAIM_URL,NETDATA_CLAIM_TOKEN,PATH,NETDATA_OFFICIAL_IMAGE,DOCKER_GRP,DOCKER_USR,NETDATA_LISTENER_PORT"
      web: "19999"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "host"
    restart: "unless-stopped"
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/var/lib/docker/volumes/netdata_netdata-cache/_data:/var/cache/netdata"
      - "/var/lib/docker/volumes/netdata_netdata-lib/_data:/var/lib/netdata"
      - "/var/lib/docker/volumes/netdata_netdata-config/_data:/etc/netdata"
      - "/etc/group:/host/etc/group"
      - "/etc/os-release:/host/etc/os-release"
      - "/etc/passwd:/host/etc/passwd"
  nodered:
    container_name: "nodered"
    entrypoint:
      - "./entrypoint.sh"
    environment:
      - "PATH=/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=16.16.0"
      - "YARN_VERSION=1.22.19"
      - "NODE_RED_VERSION=v3.0.2"
      - "NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules"
      - "FLOWS=flows.json"
    expose:
      - "1880/tcp"
    hostname: "raspberrypi4"
    image: "nodered/node-red"
    ipc: "private"
    labels:
      authors: "Dave Conway-Jones, Nick O'Leary, James Thomas, Raymond Mouthaan"
      casaos: "casaos"
      com.docker.compose.config-hash: "80b38984671a40218ff65169bc6478b4659f3c65fb4e8a60924b3a62139977e0"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:ed58160c5a2e8a1d3aa82759f0bab75d4e79aba6324376d46e8746e61e330686"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "homeserver"
      com.docker.compose.project.config_files: "/home/pi/homeserver/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/home/pi/homeserver"
      com.docker.compose.service: "nodered"
      com.docker.compose.version: "2.14.1"
      custom_id: "0a33c990-9b88-4c8c-9344-3ab4fccfa24e"
      desc: ""
      host: "192.168.1.10"
      icon: "https://icon.casaos.io/main/all/node-red.png"
      index: ""
      io.casaos.v1.app.store.id: "0"
      name: "nodered"
      org.label-schema.arch: ""
      org.label-schema.build-date: "2022-08-04T13:19:23Z"
      org.label-schema.description: "Low-code programming for event-driven applications."
      org.label-schema.docker.dockerfile: ".docker/Dockerfile.alpine"
      org.label-schema.license: "Apache-2.0"
      org.label-schema.name: "Node-RED"
      org.label-schema.url: "https://nodered.org"
      org.label-schema.vcs-ref: ""
      org.label-schema.vcs-type: "Git"
      org.label-schema.vcs-url: "https://github.com/node-red/node-red-docker"
      org.label-schema.version: "3.0.2"
      origin: "local"
      protocol: "http"
      show_env: "casaos"
      web: "1880"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "host"
    restart: "unless-stopped"
    user: "node-red"
    volumes:
      - "/home/pi/nodered/data:/data"
    working_dir: "/usr/src/node-red"
  pihole:
    container_name: "pihole"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    entrypoint:
      - "/s6-init"
    environment:
      - "TZ=America/Chicago"
      - "VIRTUAL_HOST=pi.hole"
      - "PROXY_LOCATION=pi.hole"
      - "FTLCONF_LOCAL_IPV4=127.0.0.1"
      - "PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "phpver=php"
      - "PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log"
      - "IPv6=True"
      - "S6_KEEP_ENV=1"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "FTL_CMD=no-daemon"
      - "DNSMASQ_USER=pihole"
    hostname: "pi.hole"
    image: "pihole/pihole:latest"
    ipc: "private"
    labels:
      org.opencontainers.image.created: "2023-02-15T23:57:22.460Z"
      org.opencontainers.image.description: "Pi-hole in a docker container"
      org.opencontainers.image.licenses: ""
      org.opencontainers.image.revision: "4961bf4b1ad394e62b9fee0de60d2be9c84d61b1"
      org.opencontainers.image.source: "https://github.com/pi-hole/docker-pi-hole"
      org.opencontainers.image.title: "docker-pi-hole"
      org.opencontainers.image.url: "https://github.com/pi-hole/docker-pi-hole"
      org.opencontainers.image.version: "2023.02.2"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:05"
    network_mode: "bridge"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/pi/docker-autocompose/etc-pihole:/etc/pihole"
      - "/home/pi/docker-autocompose/etc-dnsmasq.d:/etc/dnsmasq.d"
  portainer:
    container_name: "portainer"
    entrypoint:
      - "/portainer"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    hostname: "f8ec212a1931"
    image: "portainer/portainer-ce"
    ipc: "private"
    labels:
      casaos: "casaos"
      com.docker.desktop.extension.api.version: ">= 0.2.2"
      com.docker.desktop.extension.icon: "https://portainer-io-assets.sfo2.cdn.digitaloceanspaces.com/logos/portainer.png"
      com.docker.extension.additional-urls: "[{\"title\":\"Website\",\"url\":\"https://www.portainer.io?utm_campaign=DockerCon&utm_source=DockerDesktop\"\
        },{\"title\":\"Documentation\",\"url\":\"https://docs.portainer.io\"},{\"\
        title\":\"Support\",\"url\":\"https://join.slack.com/t/portainer/shared_invite/zt-txh3ljab-52QHTyjCqbe5RibC2lcjKA\"\
        }]"
      com.docker.extension.detailed-description: "<p data-renderer-start-pos=\"226\"\
        >Portainer&rsquo;s Docker Desktop extension gives you access to all of Portainer&rsquo;s\
        \ rich management functionality within your docker desktop experience.</p><h2\
        \ data-renderer-start-pos=\"374\">With Portainer you can:</h2><ul><li>See\
        \ all your running containers</li><li>Easily view all of your container logs</li><li>Console\
        \ into containers</li><li>Easily deploy your code into containers using a\
        \ simple form</li><li>Turn your YAML into custom templates for easy reuse</li></ul><h2\
        \ data-renderer-start-pos=\"660\">About Portainer&nbsp;</h2><p data-renderer-start-pos=\"\
        680\">Portainer is the worlds&rsquo; most popular universal container management\
        \ platform with more than 650,000 active monthly users. Portainer can be used\
        \ to manage Docker Standalone, Kubernetes, Docker Swarm and Nomad environments\
        \ through a single common interface. It includes a simple GitOps automation\
        \ engine and a Kube API.&nbsp;</p><p data-renderer-start-pos=\"1006\">Portainer\
        \ Business Edition is our fully supported commercial grade product for business-wide\
        \ use. It includes all the functionality that businesses need to manage containers\
        \ at scale. Visit <a class=\"sc-jKJlTe dPfAtb\" href=\"http://portainer.io/\"\
        \ title=\"http://Portainer.io\" data-renderer-mark=\"true\">Portainer.io</a>\
        \ to learn more about Portainer Business and <a class=\"sc-jKJlTe dPfAtb\"\
        \ href=\"http://portainer.io/take5?utm_campaign=DockerCon&amp;utm_source=Docker%20Desktop\"\
        \ title=\"http://portainer.io/take5?utm_campaign=DockerCon&amp;utm_source=Docker%20Desktop\"\
        \ data-renderer-mark=\"true\">get 5 free nodes.</a></p>"
      com.docker.extension.publisher-url: "https://www.portainer.io"
      com.docker.extension.screenshots: "[{\"alt\": \"screenshot one\", \"url\": \"\
        https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-1.png\"\
        },{\"alt\": \"screenshot two\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-2.png\"\
        },{\"alt\": \"screenshot three\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-3.png\"\
        },{\"alt\": \"screenshot four\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-4.png\"\
        },{\"alt\": \"screenshot five\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-5.png\"\
        },{\"alt\": \"screenshot six\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-6.png\"\
        },{\"alt\": \"screenshot seven\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-7.png\"\
        },{\"alt\": \"screenshot eight\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-8.png\"\
        },{\"alt\": \"screenshot nine\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-9.png\"\
        }]"
      custom_id: "504bdbac-efb9-4d16-915a-bf82c083f0f5"
      desc: ""
      host: "192.168.1.10"
      icon: "https://icon.casaos.io/main/all/portainer-ce.png"
      index: ""
      io.casaos.v1.app.store.id: "0"
      name: "portainer"
      org.opencontainers.image.description: "Docker container management made simple,\
        \ with the world’s most popular GUI-based container management platform."
      org.opencontainers.image.title: "Portainer"
      org.opencontainers.image.vendor: "Portainer.io"
      origin: "local"
      protocol: "http"
      show_env: "casaos,PATH"
      web: "9000"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:04"
    network_mode: "bridge"
    ports:
      - "8000:8000/tcp"
      - "9000:9000/tcp"
    restart: "unless-stopped"
    volumes:
      - "/var/lib/docker/volumes/portainer_data/_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/"
  qBittorrent:
    container_name: "qBittorrent"
    entrypoint:
      - "/init"
    environment:
      - "TZ=Europe/Rome"
      - "PUID=1000"
      - "PGID=1000"
      - "UMASK=002"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "APP_DIR=/app"
      - "CONFIG_DIR=/config"
      - "ARGS="
      - "XDG_CONFIG_HOME=/config/.config"
      - "XDG_CACHE_HOME=/config/.cache"
      - "XDG_DATA_HOME=/config/.local/share"
      - "LANG=C.UTF-8"
      - "LC_ALL=C.UTF-8"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "BUILD_ARCHITECTURE=linux-arm64"
      - "VPN_ENABLED=false"
      - "VPN_LAN_NETWORK="
      - "VPN_CONF=wg0"
      - "VPN_ADDITIONAL_PORTS="
      - "WEBUI_PORTS=8080/tcp,8080/udp"
      - "PRIVOXY_ENABLED=false"
      - "S6_SERVICES_GRACETIME=180000"
    hostname: "qBittorrent"
    image: "hotio/qbittorrent:latest"
    ipc: "private"
    labels:
      casaos: "casaos"
      custom_id: "e2e02058-040e-4ed5-95cd-0f709a191d29"
      desc: "The qBittorrent project aims to provide an open-source software alternative\
        \ to µTorrent."
      host: ""
      icon: "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/icon.png"
      index: "/"
      io.casaos.v1.app.store.id: "75"
      name: "qBittorrent"
      org.opencontainers.image.created: "2023-02-12T18:09:24Z"
      org.opencontainers.image.revision: "432481e33214bf9987e5dac44f18c918ab6103d4"
      org.opencontainers.image.source: "https://github.com/hotio/qbittorrent/tree/release"
      org.opencontainers.image.title: "hotio/qbittorrent:release"
      org.opencontainers.image.url: "https://github.com/hotio/qbittorrent/blob/master/README.md"
      org.opencontainers.image.vendor: "hotio"
      org.opencontainers.image.version: "4.5.1"
      origin: "official"
      protocol: "http"
      show_env: "casaos,TZ,PUID,PGID,UMASK"
      web: "8080"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:02"
    network_mode: "bridge"
    ports:
      - "8080:8080/tcp"
    restart: "always"
    volumes:
      - "/DATA:/DATA"
      - "/DATA/AppData/qBittorrent/config:/config"
