version: "3.6"

services:
  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    network_mode: "bridge"
    ports:
      - "3000:3000/tcp"
    restart: "unless-stopped"
    volumes:
      - "grafana-lib:/var/lib/grafana"

  homeassistant:
    container_name: "homeassistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: "host"
    privileged: true
    restart: "unless-stopped"
    volumes:
      - "~/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"

  influxdb:
    container_name: "influxdb"
    image: "influxdb"
    network_mode: "bridge"
    ports:
      - "8086:8086/tcp"
    restart: "unless-stopped"
    volumes:
      - "~/influxdb:/var/lib/influxdb2"

  netdata:
    container_name: "netdata"
    image: "netdata/netdata"
    network_mode: "bridge"
    ports:
      - "19999:19999/tcp"
    restart: "unless-stopped"
    volumes:
      - "/etc/group:/host/etc/group:ro"
      - "/etc/os-release:/host/etc/os-release:ro"
      - "/etc/passwd:/host/etc/passwd:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "netdata-cache:/var/cache/netdata"
      - "netdata-lib:/var/lib/netdata"
      - "netdata-config:/etc/netdata"

  nodered:
    container_name: "nodered"
    image: "nodered/node-red"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "~/nodered:/data"
    
  portainer:
    container_name: "portainer"
    image: "portainer/portainer-ce"
    network_mode: "bridge"
    ports:
      - "8000:8000/tcp"
      - "9000:9000/tcp"
    restart: "unless-stopped"
    volumes:
      - "portainer-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"